### ISSUE TITLE
AssertionError: Inconsistent number of segments: whisper_segments (12) != timestamped_word_segments (11)

### ISSUE THREAD

**Issue by romanzoniit** [Jeronymous/whisper-timestamped#4]
In one of the audio received an AssertionError, what could this be related to?
```
  File "C:\Users\tenet13\PycharmProjects\testWhisper\main.py", line 77, in handle_single_file
    transcribe_result = whisper_timestamped.transcribe(model, file_path, language='Russian')
  File "C:\Users\tenet13\PycharmProjects\testWhisper\venv\lib\site-packages\whisper_timestamped\transcribe.py", line 307, in transcribe_timestamped
    assert l1 == l2 or l1 == 0, f"Inconsistent number of segments: whisper_segments ({l1}) != timestamped_word_segments ({l2})"
AssertionError: Inconsistent number of segments: whisper_segments (12) != timestamped_word_segments (11)
```
![image](https://user-images.githubusercontent.com/71592522/212726463-be1ec3b3-e597-439a-970a-9ffd8768b4f4.png)

**Comment by tkorchagin** [comment]
Got the same error

**Comment by bfeist** [comment]
I saw this error on one audio file, but not on another. Could this be caused by hallucinations?

**Comment by seanth** [comment]
I have have seen this as well.
`Inconsistent number of segments: whisper_segments (489) != timestamped_word_segments (485)
Problem on end position for segment 1 ( Blah blah blah.) : 42.480000000000004 >> 37.0
Problem on end position for segment 2 ( Blah blah blah.) : 76.82 >> 67.0
Problem on end position for segment 3 ( Blah blah blah.) : 77.9 >> 74.0
Problem on end position for segment 4 ( Blah blah blah.) : 86.7 >> 78.0
Traceback (most recent call last):
  File "/Users/seanth/Lecture-Demon/lecture-daemon_data/whisper-timestamped-master/whisper_timestamped/transcribe.py", line 755, in <module>
    cli()
  File "/Users/seanth/Lecture-Demon/lecture-daemon_data/whisper-timestamped-master/whisper_timestamped/transcribe.py", line 711, in cli
    result = transcribe(
  File "/Users/seanth/Lecture-Demon/lecture-daemon_data/whisper-timestamped-master/whisper_timestamped/transcribe.py", line 252, in transcribe
    assert filter_tokens(token) == filter_tokens(segment["tokens"])
AssertionError
`
I _suspect_ it happens when the same word appears multiple times in a row, but I'm not sure. 

I can provide a link to the file that threw the error (0:58:47 in length) if wanted

**Comment by Jeronymous** [comment]
Thanks for reporting.

@romanzoniit can you please share the file on which it occurs and tell the model you are using, so that I can reproduce?

@seanth thanks for proposing to share the big file, but the one of @romanzoniit seems to be shorter, which is much better to reproduce and add to test suite.

**Comment by romanzoniit** [comment]
> Thanks for reporting.
> 
> @romanzoniit can you please share the file on which it occurs and tell the model you are using, so that I can reproduce?
> 
> @seanth thanks for proposing to share the big file, but the one of @romanzoniit seems to be shorter, which is much better to reproduce and add to test suite.

Unfortunately, I can't send the file. Maybe @seanth or @tkorchagin will send for a test

**Comment by eschmidbauer** [comment]
🖐️ also seeing this issue
![image](https://user-images.githubusercontent.com/7139998/212966283-526a72dc-3600-4ae5-968d-87e6509d4e7f.png)

**Comment by Jeronymous** [comment]
Yes I am on it...
I understand the reasons behind the issue.
Not easy to fix, but I hope to come up with a robust thing in the next days.

If anyone that can reproduce on a small audio can share the audio, it could help me to have a complete testsuite.

**Comment by seanth** [comment]
I'm actively using whisper-timestamped everyday in workflow to make video lectures for classes. I can compile a number of files that throw errors, though they will tend to be long (~45min to 75min).

**Comment by Jeronymous** [comment]
Thanks @seanth but long files won't help.

This issue should be fixed now \o/ (it was a tough one).
Feel free to re-open or open a new issue if the same assertion fails again.

As a side product, I should be able to add soon the access some "confidence score" for each word (based on logprobas).

**Comment by romanzoniit** [comment]
> Thanks @seanth but long files won't help.
> 
> This issue should be fixed now \o/ (it was a tough one). Feel free to re-open or open a new issue if the same assertion fails again.
> 
> As a side product, I should be able to add soon the access some "confidence score" for each word (based on logprobas).

it would be cool to add log_prob or exp(log_prob) for each word

**Comment by bfeist** [comment]
@Jeronymous I have a shorter file that I can provide that causes the error. Please let me know how to get it to you.

**Comment by Jeronymous** [comment]
@bfeist You could attach a zip file to this issue, if it's not a problem to share publicly the file. (you can probably edit the post to remove the attached file later on if you don't feel like sharing it forever).

But I'm worried, the issue is supposed to be fixed : is it still failing with the last version of the code? (after [this commit](https://github.com/Jeronymous/whisper-timestamped/commit/db727911c99c6558f7213a66eecf1b44a611d485))

**Comment by Jeronymous** [comment]
> it would be cool to add log_prob or exp(log_prob) for each word

@romanzoniit done
There is now a key `"confidence"` for each word.
The confidences are computed as "exp(mean(log_probas))" (on the list of subword tokens).

And also one for each segment, that is more "reliable" than the `"avg_logprob"` given by whisper
(in fact this avg logprob corresponds to the 30 sec chunk in which is included the segments, so you basically can have several segments with the same "avg_logprob", when they appear in a same 30 sec chunk)

**Comment by bfeist** [comment]
[defluttered_A11_T648_HR1U_CH2__4722_4811.zip](https://github.com/Jeronymous/whisper-timestamped/files/10451381/defluttered_A11_T648_HR1U_CH2__4722_4811.zip)
Here you go. It's an excerpt of mission control audio recorded during the Apollo 11 mission.

**Comment by Jeronymous** [comment]
Thanks a lot @bfeist that's a challenging audio for Whisper.
I've got some errors on it (different from the one mentioned in this issue). I'm on it

**Comment by bfeist** [comment]
I could possibly find more. I'm processing many of these segments through a batch process, currently using `whisper` only. I could modify the batch to use `whisper-timestamped` and send over anything that crashes.
